"""Dedicated Longstay/Finance transaction boundary. The shared Telegram repository is excluded."""
from __future__ import annotations

from typing import Any, Callable, Mapping, Protocol
from uuid import UUID


class RentTransactionPort(Protocol):
    organization_id: UUID
    ledger_revision_before: int

    def lock_entities(self, identities: list[tuple[str, UUID]]) -> None: ...
    def fetch(self, table: str, identity: UUID) -> Mapping[str, Any] | None: ...
    def insert(self, table: str, values: Mapping[str, Any]) -> None: ...
    def update_versioned(self, table: str, identity: UUID, expected_version: int, values: Mapping[str, Any], command_id: UUID) -> Mapping[str, Any]: ...
    def rows(self, sql_text: str, params: tuple[Any, ...] = ()) -> list[Mapping[str, Any]]: ...
    def balance(self, kind: str, identity: UUID) -> Mapping[str, Any] | None: ...


class RentRepositoryPort(Protocol):
    def run_command(
        self, *, command_type: str, idempotency_key: UUID, normalized_hash: str,
        expected_ledger_revision: int, plan: Callable[[RentTransactionPort, UUID], dict],
    ) -> tuple[dict, bool]: ...

    def read_rows(self, sql_text: str, params: tuple[Any, ...] = ()) -> list[Mapping[str, Any]]: ...
    def read_snapshot(self, reader: Callable[[RentTransactionPort], Any]) -> Any: ...
    def read_operator_snapshot(self, reader: Callable[[RentTransactionPort], Any]) -> Any: ...
    def lookup(self, command_type: str, key: UUID) -> dict | None: ...
